OPERATION_1 string : Channel
      .fromPath(params.fasta)
      .ifEmpty { exit 1, "FASTA annotation file not found: ${params.fasta}" }
      .into { fasta_index; fasta_dragen }
OPERATION_1 origin : [['params.fasta', 'A']]
OPERATION_1 gives  : [['fasta_index', 'P'], ['fasta_dragen', 'P']]


OPERATION_2 string : Channel
      .fromPath(params.ref)
      .ifEmpty { exit 1, "Folder containing indexes for reference genome generated by Dragen not found: ${params.ref}" }
      .set { ref_dragen }
OPERATION_2 origin : [['params.ref', 'A']]
OPERATION_2 gives  : [['ref_dragen', 'P']]


OPERATION_3 string : Channel
    .fromFilePairs(reads, size: 2)
    .ifEmpty { exit 1, "Cannot find any reads matching: ${reads}" }
    .merge(fasta_dragen)
    .set { reads_fasta_dragen}
OPERATION_3 origin : [['fasta_dragen', 'P'], ['reads, size: 2', 'A']]
OPERATION_3 gives  : [['reads_fasta_dragen', 'P']]


OPERATION_4 string : dragen = reads_fasta_dragen.combine(ref_dragen)
OPERATION_4 origin : [['reads_fasta_dragen', 'P'], ['ref_dragen', 'P']]
OPERATION_4 gives  : [['dragen', 'P']]


